In [81]:
import pandas as pd
from glob import glob

In [82]:
dirr = 'C:/Users/shic/Desktop/shinhan_simon/google_drive/crawler_data/estate_trend/new/'

In [83]:
list_files = glob(dirr + '*.csv')
list_files

['C:/Users/shic/Desktop/shinhan_simon/google_drive/crawler_data/estate_trend/new\\부동산시장_소비심리지수_20210824151628.csv',
 'C:/Users/shic/Desktop/shinhan_simon/google_drive/crawler_data/estate_trend/new\\주택매매시장_소비심리지수_20210824143933.csv',
 'C:/Users/shic/Desktop/shinhan_simon/google_drive/crawler_data/estate_trend/new\\주택시장_소비심리지수_20210824143844.csv',
 'C:/Users/shic/Desktop/shinhan_simon/google_drive/crawler_data/estate_trend/new\\주택전세시장_소비심리지수_20210824144008.csv',
 'C:/Users/shic/Desktop/shinhan_simon/google_drive/crawler_data/estate_trend/new\\토지시장_소비심리지수_20210824143909.csv']

In [84]:
list_files

['C:/Users/shic/Desktop/shinhan_simon/google_drive/crawler_data/estate_trend/new\\부동산시장_소비심리지수_20210824151628.csv',
 'C:/Users/shic/Desktop/shinhan_simon/google_drive/crawler_data/estate_trend/new\\주택매매시장_소비심리지수_20210824143933.csv',
 'C:/Users/shic/Desktop/shinhan_simon/google_drive/crawler_data/estate_trend/new\\주택시장_소비심리지수_20210824143844.csv',
 'C:/Users/shic/Desktop/shinhan_simon/google_drive/crawler_data/estate_trend/new\\주택전세시장_소비심리지수_20210824144008.csv',
 'C:/Users/shic/Desktop/shinhan_simon/google_drive/crawler_data/estate_trend/new\\토지시장_소비심리지수_20210824143909.csv']

In [85]:
df_list = []
cate_list = ['부동산시장','주택매매시장','주택시장_소비심리지수','주택전세시장_소비심리지수','토지시장_소비심리지수']
for file_num in range(len(list_files)):
    tmp_df = pd.read_csv(list_files[file_num],encoding='CP949')
    tmp_df['category'] = cate_list[file_num]
    tmp_df = pd.melt(tmp_df,id_vars=['시도별(1)','시도별(2)','category'])
    df_list.append(tmp_df)

In [86]:
df = pd.concat(df_list,axis=0)
df

     시도별(1)   시도별(2)     category  variable  value
0        전국       소계        부동산시장  2012. 01  109.1
1       수도권       소계        부동산시장  2012. 01  104.4
2       수도권    서울특별시        부동산시장  2012. 01  106.3
3       수도권    인천광역시        부동산시장  2012. 01   99.6
4       수도권      경기도        부동산시장  2012. 01  104.3
...     ...      ...          ...       ...    ...
2275   비수도권     전라북도  토지시장_소비심리지수  2021. 06  104.8
2276   비수도권     전라남도  토지시장_소비심리지수  2021. 06  101.8
2277   비수도권     경상북도  토지시장_소비심리지수  2021. 06  100.3
2278   비수도권     경상남도  토지시장_소비심리지수  2021. 06   91.5
2279   비수도권  제주특별자치도  토지시장_소비심리지수  2021. 06   96.7

[11400 rows x 5 columns]

In [87]:
df_pivot = df.pivot(index=['시도별(1)','시도별(2)','variable'],columns='category',values='value').reset_index()
df_pivot['variable'] = df_pivot['variable'].str.replace('. ','')

C:\Users\shic\anaconda3\envs\simon_env\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: The default value of regex will change from True to False in a future version.

category,시도별(1),시도별(2),variable,부동산시장,주택매매시장,주택시장_소비심리지수,주택전세시장_소비심리지수,토지시장_소비심리지수
0,비수도권,강원도,201201,121.1,123.5,124.3,125.2,92.4
1,비수도권,강원도,201202,129.8,134.8,133.5,132.1,97.1
2,비수도권,강원도,201203,123.7,126.7,127.1,127.6,92.9
3,비수도권,강원도,201204,121.1,127.1,124.5,122.0,90.0
4,비수도권,강원도,201205,117.0,121.3,120.4,119.6,86.1
...,...,...,...,...,...,...,...,...
2275,전국,소계,202102,123.4,135.5,125.5,115.5,104.0
2276,전국,소계,202103,120.1,131.6,121.7,111.8,105.5
2277,전국,소계,202104,117.8,128.4,119.4,110.4,103.4
2278,전국,소계,202105,121.7,133.8,123.7,113.5,103.8
2279,전국,소계,202106,125.2,137.7,127.4,117.0,106.2

In [91]:
df_pivot.columns = ['Sidonm','Signgu_Nm','Base_Ym','estate_trend','house_trade_trend','house_trend','house_rent_trend','land_trend']
df_pivot

,Sidonm,Signgu_Nm,Base_Ym,estate_trend,house_trade_trend,house_trend,house_rent_trend,land_trend
0,비수도권,강원도,201201,121.1,123.5,124.3,125.2,92.4
1,비수도권,강원도,201202,129.8,134.8,133.5,132.1,97.1
2,비수도권,강원도,201203,123.7,126.7,127.1,127.6,92.9
3,비수도권,강원도,201204,121.1,127.1,124.5,122.0,90.0
4,비수도권,강원도,201205,117.0,121.3,120.4,119.6,86.1
...,...,...,...,...,...,...,...,...
2275,전국,소계,202102,123.4,135.5,125.5,115.5,104.0
2276,전국,소계,202103,120.1,131.6,121.7,111.8,105.5
2277,전국,소계,202104,117.8,128.4,119.4,110.4,103.4
2278,전국,소계,202105,121.7,133.8,123.7,113.5,103.8
2279,전국,소계,202106,125.2,137.7,127.4,117.0,106.2

In [92]:
df_pivot.to_csv(dirr + 'df_bind.csv',index=False,encoding='UTF-8')